# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Auto Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: SunshineGameFinder

    - name: Build project
      run: dotnet build --no-restore -c Release
      working-directory: SunshineGameFinder

    - name: Publish for Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained true -o publish
      working-directory: SunshineGameFinder

    - name: Generate release tag
      id: tag
      run: echo "TAG_NAME=auto-$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Automatic Release from push to main
        draft: false
        prerelease: false

    - name: Upload .exe to Release
      uses: softprops/action-gh-release@v1
      with:
        files: SunshineGameFinder/publish/SunshineGameFinder.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
